import type { Metadata } from "next";
import { Raleway } from "next/font/google";


import "@/lib/styles/base.scss";
import "@/lib/styles/mixin.scss";

import Header from "@/components/Header";
import Footer from "@/components/Footer";

const raleway = Raleway({
    subsets: ["latin"],
    variable: "--font-raleway",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={raleway.className}>
      <Header />
      <main>
        {children}
      </main>
      <Footer />
      </body>
    </html>
  );
}
